
#[cfg(windows)]
use winres::WindowsResource;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    embed_icon_if_for_windows()?;

    Ok(())
}


fn embed_icon_if_for_windows() -> Result<(), Box<dyn std::error::Error>> {
  #[cfg(windows)]
  {
      WindowsResource::new()
        .set_icon("target/HTIR.ico") // Generated by btool/icon_gen.py
        .set("ProductName", "HTIR Client")
        .set("LegalCopyright", "\u{00a9} 2022-2023 Jeffrey McAteer <jeffrey.p.mcateer@gmail.com> All Rights Reserved")
        .set("", "")
        .set("", "")
        .compile()?;
  }
  Ok(())
}
