[package]
name = "htir"
version = "0.1.0"
edition = "2021"

[lib]
name = "htir"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"


[dependencies]
tokio = { version = "1", features = ["full"] }
sqlite = "0.26"

dirs = "4.0"





