[package]
name = "htir_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "htir"
crate-type = ["cdylib"]

[dependencies]
htir = { path = ".." }
pyo3 = { version = "0.16.3", features = ["extension-module"] }

